// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYvKBH9RmBL4xq2aWaqFROH6sScfW_e9Q',
    appId: '1:1010428768816:web:5e7257a3bd33b23a11b3f5',
    messagingSenderId: '1010428768816',
    projectId: 'makemeover-1cf53',
    authDomain: 'makemeover-1cf53.firebaseapp.com',
    storageBucket: 'makemeover-1cf53.firebasestorage.app',
    measurementId: 'G-7HJCNH2HH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6o50rqA-cTt9pr8bDANHqRAn1UN98S64',
    appId: '1:1010428768816:android:253ba7817ef6c20e11b3f5',
    messagingSenderId: '1010428768816',
    projectId: 'makemeover-1cf53',
    storageBucket: 'makemeover-1cf53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXc3mMX4PpHOlm94_iivPZQ4k-wroy9-Q',
    appId: '1:1010428768816:ios:a21cc9dd008d5b5811b3f5',
    messagingSenderId: '1010428768816',
    projectId: 'makemeover-1cf53',
    storageBucket: 'makemeover-1cf53.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXc3mMX4PpHOlm94_iivPZQ4k-wroy9-Q',
    appId: '1:1010428768816:ios:a21cc9dd008d5b5811b3f5',
    messagingSenderId: '1010428768816',
    projectId: 'makemeover-1cf53',
    storageBucket: 'makemeover-1cf53.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYvKBH9RmBL4xq2aWaqFROH6sScfW_e9Q',
    appId: '1:1010428768816:web:c2d8f289e838c5c211b3f5',
    messagingSenderId: '1010428768816',
    projectId: 'makemeover-1cf53',
    authDomain: 'makemeover-1cf53.firebaseapp.com',
    storageBucket: 'makemeover-1cf53.firebasestorage.app',
    measurementId: 'G-1RRKNQVLFF',
  );
}
